EXAMPLE_QUERIES = [
    "Moonlight by the sea",
    "Orientalism",
    "Ancient Rome",
    "Martin Luther",
    "War",
    "Inside a cathedral",
    "Fauvism",
    "Cubism",
    "Old man with beard",
    "Death",
    "Paris",
    "Reading child",
    "Raw meat",
    "Nature morte",
    "Wooden bridge",
    "Winter landscape",
    "Woman by a window",
    "Red",
]
