# Generated by Django 5.1.5 on 2025-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_slug', models.CharField(max_length=10)),
                ('museum_object_id', models.CharField(max_length=100)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('raw_xml', models.TextField(blank=True, null=True)),
                ('raw_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('museum_slug', 'museum_object_id')},
            },
        ),
    ]
