# Generated by Django 5.1.5 on 2025-07-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataraw',
            name='embedding_model',
        ),
    ]
