# Generated by Django 5.1.5 on 2025-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_remove_metadataraw_embedding_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataraw',
            name='raw_xml',
        ),
    ]
