# Generated by Django 5.1.5 on 2025-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_transformeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='searchable_work_types',
            field=models.JSONField(),
        ),
    ]
