# Generated by Django 5.1.5 on 2025-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_transformeddata_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='museum_frontend_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
