# Generated by Django 5.1.5 on 2025-08-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_transformeddata_museum_frontend_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeddata',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
