# Generated by Django 5.1.5 on 2025-08-17 06:54

from django.db import migrations


def fill_null_raw_json(apps, schema_editor):
    MetaDataRaw = apps.get_model('etl', 'MetaDataRaw')
    # Update any null raw_json fields with empty dict
    updated_count = MetaDataRaw.objects.filter(raw_json__isnull=True).update(raw_json={})
    print(f"Updated {updated_count} records with null raw_json")


def reverse_fill_null_raw_json(apps, schema_editor):
    # Reverse operation (set back to null if needed)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0007_alter_transformeddata_title"),
    ]

    operations = [
        migrations.RunPython(fill_null_raw_json, reverse_fill_null_raw_json),
    ]
