# Generated by Django 5.1.5 on 2025-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_fill_null_raw_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='raw_json',
            field=models.JSONField(),
        ),
    ]
