# Generated by Django 5.1.5 on 2025-08-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_alter_metadataraw_raw_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataraw',
            name='processed_at',
        ),
    ]
