# Generated by Django 5.1.5 on 2025-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_remove_metadataraw_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataraw',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
