# Generated by Django 5.1.5 on 2025-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0011_metadataraw_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadataraw',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='metadataraw',
            constraint=models.UniqueConstraint(fields=('museum_slug', 'museum_object_id'), name='uniq_raw_museum_object'),
        ),
    ]
