# Generated by Django 5.1.5 on 2025-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0012_alter_metadataraw_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='source_raw_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
