# Generated by Django 5.1.5 on 2025-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_transformeddata_source_raw_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeddata',
            name='source_raw_hash',
            field=models.CharField(max_length=64),
        ),
    ]
