# Generated by Django 5.1.5 on 2025-08-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_alter_transformeddata_source_raw_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataraw',
            old_name='fetched_at',
            new_name='created_at',
        ),
    ]
