# Generated by Django 5.1.5 on 2025-08-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0015_rename_fetched_at_metadataraw_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformeddata',
            old_name='transformed_at',
            new_name='created_at',
        ),
    ]
