# Generated by Django 5.1.5 on 2025-08-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0016_rename_transformed_at_transformeddata_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformeddata',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
