# Generated by Django 5.1.5 on 2025-08-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0017_rename_updated_at_transformeddata_last_updated'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transformeddata',
            name='unique_museum_object',
        ),
    ]
