# Generated by Django 5.1.5 on 2025-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0018_remove_transformeddata_unique_museum_object'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metadataraw',
            index=models.Index(fields=['museum_slug'], name='etl_metadat_museum__8181f7_idx'),
        ),
        migrations.AddIndex(
            model_name='metadataraw',
            index=models.Index(fields=['raw_hash'], name='etl_metadat_raw_has_44e035_idx'),
        ),
        migrations.AddIndex(
            model_name='transformeddata',
            index=models.Index(fields=['source_raw_hash'], name='etl_transfo_source__f536a6_idx'),
        ),
        migrations.AddIndex(
            model_name='transformeddata',
            index=models.Index(fields=['museum_slug'], name='etl_transfo_museum__848d18_idx'),
        ),
    ]
