# Generated by Django 5.1.5 on 2025-08-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0019_metadataraw_etl_metadat_museum__8181f7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformeddata',
            name='museum_frontend_url',
        ),
        migrations.RemoveField(
            model_name='transformeddata',
            name='object_url',
        ),
    ]
