# Generated by Django 5.1.5 on 2025-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0020_remove_transformeddata_museum_frontend_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='thumbnail_url_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of thumbnail_url to detect changes', max_length=64, null=True),
        ),
    ]
