# Generated by Django 5.1.5 on 2025-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0021_transformeddata_thumbnail_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='raw_hash',
            field=models.CharField(help_text='SHA 256 hash of the stored raw_json', max_length=64),
        ),
    ]
