# Generated by Django 5.1.5 on 2025-09-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0023b_deduplicate_object_numbers'),
    ]

    operations = [
        # Remove old constraint first
        migrations.RemoveConstraint(
            model_name='metadataraw',
            name='uniq_raw_museum_object',
        ),

        # Make object_number field required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(max_length=100, help_text="Stable public identifier (accession number)"),
        ),

        # Add new constraint based on object_number
        migrations.AddConstraint(
            model_name='metadataraw',
            constraint=models.UniqueConstraint(
                fields=['museum_slug', 'object_number'],
                name='uniq_raw_museum_object_number',
            ),
        ),
    ]
