# Generated by Django 5.1.5 on 2025-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0024_make_object_number_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataraw',
            name='is_transformed',
            field=models.BooleanField(default=False, help_text='Whether this record has been transformed yet'),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(max_length=100),
        ),
    ]
