# Generated by Django 5.1.5 on 2025-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0025_add_is_transformed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='museum_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
