# Generated by Django 5.1.5 on 2025-09-19 06:08

from django.db import migrations


def nullify_museum_object_id_for_smk_cma(apps, schema_editor):
    """Set museum_object_id to null for SMK and CMA records since we now use object_number as primary identifier"""
    MetaDataRaw = apps.get_model('etl', 'MetaDataRaw')

    # Update SMK records
    smk_updated = MetaDataRaw.objects.filter(museum_slug='smk').update(museum_object_id=None)
    print(f"Set museum_object_id to null for {smk_updated} SMK records")

    # Update CMA records
    cma_updated = MetaDataRaw.objects.filter(museum_slug='cma').update(museum_object_id=None)
    print(f"Set museum_object_id to null for {cma_updated} CMA records")

    print(f"Total updated: {smk_updated + cma_updated} records")


def reverse_nullify_museum_object_id(apps, schema_editor):
    """Reverse migration - cannot restore original museum_object_id values"""
    print("WARNING: Cannot reverse this migration - original museum_object_id values were not preserved")


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0026_make_museum_object_id_optional'),
    ]

    operations = [
        migrations.RunPython(
            nullify_museum_object_id_for_smk_cma,
            reverse_nullify_museum_object_id,
        ),
    ]
