# Generated by Django 5.1.5 on 2025-09-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0027_nullify_museum_object_id_for_smk_cma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataraw',
            old_name='museum_object_id',
            new_name='museum_db_id',
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='First fetched timestamp'),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(help_text='Stable puclic artwork identifier', max_length=100),
        ),
    ]
