# Generated by Django 5.1.5 on 2025-09-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0028_remove_metadataraw_museum_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metadataraw',
            name='etl_metadat_raw_has_44e035_idx',
        ),
        migrations.RemoveField(
            model_name='metadataraw',
            name='raw_hash',
        ),
    ]
