# Generated by Django 5.1.5 on 2025-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0029_remove_metadataraw_etl_metadat_raw_has_44e035_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='museum_db_id',
            field=models.CharField(blank=True, help_text='Optional museum database ID', max_length=100, null=True),
        ),
    ]
