# Generated by Django 5.1.5 on 2025-09-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0030_alter_metadataraw_museum_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformeddata',
            name='raw_data',
        ),
    ]
