# Generated by Django 5.1.5 on 2025-09-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0031_remove_transformeddata_raw_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transformeddata',
            name='etl_transfo_source__f536a6_idx',
        ),
        migrations.RemoveField(
            model_name='transformeddata',
            name='source_raw_hash',
        ),
    ]
