# Generated by Django 5.1.5 on 2025-09-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0032_remove_transformeddata_etl_transfo_source__f536a6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='First transformed timestamp'),
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
    ]
