# Generated by Django 5.1.5 on 2025-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0033_alter_transformeddata_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transformeddata",
            constraint=models.UniqueConstraint(
                fields=("museum_slug", "object_number"),
                name="uniq_transformed_museum_object_number",
            ),
        ),
    ]
