# Generated by Django 5.1.5 on 2025-09-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0034_transformeddata_uniq_transformed_museum_object_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformeddata',
            name='thumbnail_url_hash',
        ),
    ]
