# Generated by Django 5.1.5 on 2025-09-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0035_remove_transformeddata_thumbnail_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='vector_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
