# Generated by Django 5.1.5 on 2025-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0036_transformeddata_vector_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeddata',
            name='museum_db_id',
            field=models.CharField(blank=True, help_text='Optional museum database ID', max_length=100, null=True),
        ),
    ]
