# Generated by Django 5.1.5 on 2025-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0037_alter_transformeddata_museum_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataraw',
            name='is_transformed',
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='work_types',
            field=models.JSONField(default=list, help_text='List of work types in original language'),
        ),
    ]
