# Generated by Django 5.1.5 on 2025-10-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0038_remove_metadataraw_is_transformed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformeddata',
            name='vector_loaded',
        ),
    ]
