# Generated by Django 5.1.5 on 2025-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0039_remove_transformeddata_vector_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='museum_db_id',
            field=models.CharField(blank=True, help_text='Internal museum database ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(help_text='Stable and unique puclic artwork identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='museum_db_id',
            field=models.CharField(blank=True, help_text='Internal museum database ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='object_number',
            field=models.CharField(help_text='Stable and unique puclic artwork identifier', max_length=100),
        ),
    ]
