# Generated by Django 5.1.5 on 2025-10-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0041_alter_metadataraw_museum_db_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='museum_db_id',
            field=models.CharField(help_text='Internal museum database ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='transformeddata',
            name='museum_db_id',
            field=models.CharField(help_text='Internal museum database ID', max_length=100),
        ),
    ]
