# Generated by Django 5.1.5 on 2025-10-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0042_alter_metadataraw_museum_db_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='image_load_failed',
            field=models.BooleanField(default=False),
        ),
    ]
