# Generated by Django 5.1.5 on 2025-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0043_transformeddata_image_load_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataraw',
            name='object_number',
            field=models.CharField(help_text='Stable and unique public artwork identifier', max_length=100),
        ),
    ]
