# Generated by Django 5.1.5 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0044_alter_metadataraw_object_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformeddata",
            name="embedding_load_failed",
            field=models.BooleanField(default=False),
        ),
    ]
