# Generated by Django 5.1.14 on 2026-01-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0045_add_embedding_load_failed_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformeddata',
            old_name='artist',
            new_name='artists',
        ),
    ]
