# Generated by Django 5.1.14 on 2026-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0046_rename_artist_to_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeddata',
            name='object_number',
            field=models.CharField(help_text='Stable and unique public artwork identifier', max_length=100),
        ),
    ]
