from django.utils.translation import gettext_lazy as _

WORK_TYPE_LABELS: dict[str, str] = {
    "aquatint": _("Aquatints"),
    "bust": _("Busts"),
    "design": _("Designs"),
    "drawing": _("Drawings"),
    "guache": _("Guaches"),
    "miniature": _("Miniatures"),
    "painting": _("Paintings"),
    "pastel": _("Pastels"),
    "print": _("Prints"),
    "watercolor": _("Watercolors"),
}

EXAMPLE_QUERIES: dict[str, list[str]] = {
    "chosen": [
        _("Ship in a storm"),
        _("Reading child"),
        _("Orientalism"),
        _("Inside cathedral"),
        _("Ancient Rome"),
        _("War"),
        _("Music"),
        _("Moonlight by the sea"),
        _("Fauvism"),
        _("Cubism"),
        _("Blue dress"),
        _("Death"),
        _("Elephant"),
        _("Hindu deity"),
        _("Painter"),
        _("Male model"),
        _("Fish still life"),
        _("Anatomy lesson"),
        _("Winter landscape"),
        _("Colorful flowers in a vase"),
        _("Crucifixion"),
        _("Breastfeeding"),
        _("Calligraphy and landscape"),
        _("Persian carpet"),
        _("Mourning"),
    ],
    "candidates": [
        _("Buddha"),
        _("Dead birds"),
        _("Bible scene"),
        _("Camel"),
        _("Rembrandt"),
        _("Martin Luther"),
        _("Windmill"),
        _("Map of a fortress"),
    ],
}
