EXAMPLE_QUERIES: dict[str, list[str]] = {
    "chosen": [
        "Ship in a storm",
        "Reading child",
        "Orientalism",
        "Inside cathedral",
        "Ancient Rome",
        "War",
        "Music",
        "Moonlight by the sea",
        "Fauvism",
        "Cubism",
        "Blue dress",
        "Death",
        "Elephant",
        "Hindu deity",
        "Painter",
        "Male model",
        "Fish still life",
        "Anatomy lesson",
        "Winter landscape",
        "Colorful flowers in a vase",
        "Crucifixion",
        "Breastfeeding",
        "Calligraphy and landscape",
        "Persian carpet",
        "Mourning",
    ],
    "candidates": [
        "Buddha",
        "Dead birds",
        "Bible scene",
        "Camel",
        "Rembrandt",
        "Martin Luther",
        "Windmill",
        "Map of a fortress",
    ],
}
