# A set work types that the user can filter on in the search
SEARCHABLE_WORK_TYPES = set(
    [
        "drawing",
        "painting",
        "watercolor",
        "print",
        "design",
        "bust",
        "pastel",
        "aquatint",
        "guache",
        "miniature",
    ]
)

# Dictionary for work types that need translation or standardized naming
# Used both at runtime (to translate and standardize the work type tags shown on the artwork cards) and in the
# ETL transformation process to find searchable work types from various input work type names.
# NB: The reason we apply this mapping at runtime is that we want to be able to add new translations or edit
# existing ones without having to re-run the entire ETL process.
WORK_TYPES_DICT = {
    "ornamenttekening": "ornamental drawing",
    "albumblad": "album leaf",
    "zijpaneel": "side panel",
    "aquarel": "watercolor",
    "penschildering": "pen painting",
    "decoratiestuk": "decorative piece",
    "historieplaat": "history panel",
    "interieuronderdeel": "interior element",
    "tondi": "tondo",
    "betimmering": "paneling",
    "heraldisch object": "heraldic object",
    "memoriestuk": "memorial piece",
    "historieprent": "historical print",
    "schroefdaalder": "screw daalder (coin type)",
    "reproductie": "reproduction",
    "schoorsteen": "chimney",
    "perspectiefkast": "perspective box",
    "wrijfprent": "rubbing print",
    "beschilderde katoen": "painted cotton",
    "uithangbord": "signboard",
    "kopie naar fresco": "copy after fresco",
    "kopie naar tekening": "copy after drawing",
    "kopie naar prent": "copy after print",
    "schetsboekblad": "sketchbook page",
    "Boeddha-beeld": "buddha statue",
    "theebus": "tea caddy",
    "tegning": "drawing",
    "maleri": "painting",
    "akvarel": "watercolor",
    "buste": "bust",
    "akvatinte": "aquatint",
    "altertavle (maleri)": "altarpiece",
    "grafik": "print",
    "boekillustratie (ontwerp)": "book illustration (design)",
    "figuurstudie": "figure study",
    "boekrug (ontwerp)": "book spine (design)",
    "nieuwjaarswens": "New Year's wish",
    "menukaart": "menu card",
    "kostuumstudie": "costume study",
    "kostuumprent": "costume print",
    "titelpagina": "title page",
    "historisch objectvoorstelling": "historical object representation",
    "illustratie (ontwerp)": "illustration (design)",
    "muziekblad": "music sheet",
    "dierstudie": "animal study",
    "schetsblad": "sketch sheet",
    "architectuurtekening": "architectural drawing",
    "voorstudie (schilderij)": "preparatory study (painting)",
    "prentbriefkaart": "illustrated postcard",
    "waaierblad": "fan leaf",
    "tekst": "text",
    "voorstudie (prent)": "preparatory study (print)",
    "verzamelalbum": "collection album",
    "kindertekening": "children's drawing",
    "boekomslag (ontwerp)": "book cover (design)",
    "wensbrief": "wish letter",
    "kunsthistorische verhandeling": "art historical treatise",
    "boekillustratie": "book illustration",
    "tools": "tool",
    "kopie naar schilderij": "copy after painting",
    "kwitantie": "receipt",
    "decoratief object": "decorative object",
    "aantekening": "note",
    "kunstenaarskarikatuur": "artist's caricature",
    #### Used by MET #####
    "paintings": "painting",
    "miniatures": "miniature",
    "pastels": "pastel",
    "oil sketches on paper": "oil sketch on paper",
    "drawings": "drawing",
    "prints": "print",
    ###################
}
