EXAMPLE_QUERIES = [
    "Reading child",
    "Orientalism",
    "Blue dress",
    "Inside cathedral",
    "Ancient Rome",
    "War",
    "Music",
    "Raw meat",
    "Moonlight by the sea",
    "Martin Luther",
    "Fauvism",
    "Cubism",
    "Old man",
    "Death",
    "Nature morte",
    "Winter landscape",
    "Woman by a window",
    "Ship in a storm",
]
