# Generated by Django 5.1.5 on 2025-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
