# Generated by Django 5.1.5 on 2025-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0002_searchlog_username_alter_searchlog_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
