# Generated by Django 5.1.5 on 2025-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artsearch", "0003_alter_searchlog_id_alter_searchlog_query_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("museum_slug", models.CharField(max_length=10)),
                ("museum_object_id", models.CharField(max_length=100)),
                ("raw_json", models.JSONField()),
                ("raw_hash", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("museum_slug", "museum_object_id")},
            },
        ),
    ]
