# Generated by Django 5.1.5 on 2025-07-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0004_rawmetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMetaData',
            new_name='MetaDataRaw',
        ),
    ]
