# Generated by Django 5.1.5 on 2025-07-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0005_rename_rawmetadata_metadataraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataraw',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metadataraw',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadataraw',
            name='raw_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadataraw',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
