# Generated by Django 5.1.5 on 2025-07-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0006_metadataraw_embedding_model_metadataraw_processed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaDataRaw',
        ),
    ]
