# Generated by Django 5.1.5 on 2025-10-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0010_alter_artworkworktypemapping_qdrant_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkStatistics',
        ),
        migrations.DeleteModel(
            name='ArtworkWorkTypeMapping',
        ),
    ]
