# Generated by Django 5.1.5 on 2025-11-03 04:19

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0011_delete_artworkstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_slug', models.CharField(max_length=10)),
                ('object_number', models.CharField(help_text='Stable and unique public artwork identifier', max_length=100)),
                ('searchable_work_types', models.JSONField(help_text='List of searchable work types for this artwork')),
            ],
            options={
                'indexes': [models.Index(fields=['museum_slug'], name='artsearch_a_museum__4ced02_idx'), django.contrib.postgres.indexes.GinIndex(fields=['searchable_work_types'], name='idx_searchable_work_types_gin')],
                'constraints': [models.UniqueConstraint(fields=('museum_slug', 'object_number'), name='uniq_stats_museum_object')],
            },
        ),
    ]
