# Generated by Django 5.1.5 on 2025-11-03 08:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0012_artworkstats'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artworkstats',
            name='idx_searchable_work_types_gin',
        ),
        migrations.AddIndex(
            model_name='artworkstats',
            index=django.contrib.postgres.indexes.GinIndex(fields=['searchable_work_types'], name='idx_searchable_work_types_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
