# Generated by Django 5.1.14 on 2025-11-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0013_remove_artworkstats_idx_searchable_work_types_gin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_slug', models.CharField(max_length=10)),
                ('object_number', models.CharField(help_text='Stable and unique public artwork identifier', max_length=100)),
                ('description', models.TextField(help_text='AI-generated artwork description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('museum_slug', 'object_number'), name='uniq_description_museum_object')],
            },
        ),
    ]
