# Generated by Django 5.1.14 on 2025-11-24 15:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0014_artworkdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkstats',
            name='artist',
            field=models.JSONField(default=list, help_text='List of artist names for this artwork'),
        ),
        migrations.AddIndex(
            model_name='artworkstats',
            index=django.contrib.postgres.indexes.GinIndex(fields=['artist'], name='idx_artist_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
