# Generated by Django 5.1.14 on 2025-11-25 03:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0015_artworkstats_artist_artworkstats_idx_artist_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artworkstats',
            name='idx_artist_gin',
        ),
        migrations.RemoveField(
            model_name='artworkstats',
            name='artist',
        ),
        migrations.AddField(
            model_name='artworkstats',
            name='artists',
            field=models.JSONField(default=list, help_text='List of artist names for this artwork'),
        ),
        migrations.AddIndex(
            model_name='artworkstats',
            index=django.contrib.postgres.indexes.GinIndex(fields=['artists'], name='idx_artists_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
