# Generated by Django 5.1.14 on 2026-01-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0016_rename_artist_to_artists'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artworkstats',
            name='idx_artists_gin',
        ),
        migrations.RemoveField(
            model_name='artworkstats',
            name='artists',
        ),
    ]
