# Generated by Django 5.1.14 on 2026-01-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0017_remove_artworkstats_idx_artists_gin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this query is shown on the homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (before randomization)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Example Query',
                'verbose_name_plural': 'Example Queries',
                'ordering': ['display_order', 'query'],
            },
        ),
    ]
