# Generated by Django 5.1.14 on 2026-01-25 08:09

from django.db import migrations


INITIAL_QUERIES = [
    "Ship in a storm",
    "Reading child",
    "Cubism",
    "Inside cathedral",
    "Ancient Rome",
    "Orientalism",
    "Blue dress",
    "War",
    "Fish still life",
    "Mourning",
    "Human anatomy",
    "Moonlight by the sea",
    "Music",
    "Death",
    "Hindu deity",
    "Elephant",
    "Painter",
    "Fauvism",
    "Colorful flowers in a vase",
    "Winter landscape",
    "Crucifixion",
    "Calligraphy and landscape",
    "Breastfeeding",
    "Buddha",
    "Dead birds",
    "Bible scene",
    "Persian carpet",
    "Camel",
    "Rembrandt",
    "Martin Luther",
    "Windmill",
    "Map of a fortress",
]


def populate_example_queries(apps, schema_editor):
    ExampleQuery = apps.get_model("artsearch", "ExampleQuery")
    for query in INITIAL_QUERIES:
        ExampleQuery.objects.create(query=query, is_active=True)


def remove_example_queries(apps, schema_editor):
    ExampleQuery = apps.get_model("artsearch", "ExampleQuery")
    ExampleQuery.objects.filter(query__in=INITIAL_QUERIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("artsearch", "0018_add_example_query"),
    ]

    operations = [
        migrations.RunPython(populate_example_queries, remove_example_queries),
    ]
