# Generated by Django 5.1.14 on 2026-01-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0019_populate_example_queries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplequery',
            options={'ordering': ['query'], 'verbose_name': 'Example Query', 'verbose_name_plural': 'Example Queries'},
        ),
        migrations.RemoveField(
            model_name='examplequery',
            name='display_order',
        ),
    ]
