# Generated by Django 5.1.15 on 2026-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0020_remove_example_query_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplequery',
            name='all_work_types',
            field=models.BooleanField(default=False, help_text='If true, select all work types when clicked. If false, select only paintings.'),
        ),
    ]
