# Generated by Django 5.1.15 on 2026-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsearch', '0021_examplequery_all_work_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Raw JSON string of map data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
