SUPPORTED_MUSEUMS = [
    {
        "slug": "smk",
        "short_name": "SMK",
        "vernacular_name": "Statens Museum for Kunst",
        "full_name": "National Gallery of Denmark",
    },
    {
        "slug": "cma",
        "short_name": "CMA",
        "full_name": "Cleveland Museum of Art",
    },
    {
        "slug": "rma",
        "short_name": "RMA",
        "full_name": "Rijksmuseum",
    },
]

# A set work types that the user can filter on in the search if there are any works of that type
# at the chosen museum
SEARCHABLE_WORK_TYPES = set(
    [
        "drawing",
        "painting",
        "watercolor",
        "print",
        "design",
        "bust",
        "pastel",
        "altarpiece",
        "aquatint",
        "guache",
        "miniature",
    ]
)


EXAMPLE_QUERIES: dict[str, list[str]] = {
    "smk": [
        "Reading child",
        "Orientalism",
        "Blue dress",
        "Inside cathedral",
        "Ancient Rome",
        "War",
        "Music",
        "Raw meat",
        "Moonlight by the sea",
        "Martin Luther",
        "Fauvism",
        "Cubism",
        "Death",
        "Nature morte",
        "Winter landscape",
        "Woman by a window",
        "Ship in a storm",
        "Painter",
        "Sorrow",
    ],
    "cma": [
        "Hindu deity",
        "Impressionism",
        "Arabia",
        "Inside cathedral",
        "Calligraphy",
        "Elephant",
        "Reading",
        "Birds",
        "Ancient Rome",
        "War",
        "Music",
        "Raw meat",
        "Moonlight by the sea",
        "Cubism",
        "Nature morte",
        "Winter landscape",
        "Ship in a storm",
        "Crucifixion",
    ],
    "rma": [
        "Dead birds",
        "Mill",
        "Orientalism",
        "Map of a fortress",
        "Breastfeeding",
        "Cattle",
        "Family portrait",
        "Ship in a storm",
        "War",
        "Music",
        "Dance",
        "Anatomy lesson",
        "Rembrandt",
        "Oriental carpet",
        "Old man reading",
        "Fish still life",
        "Flowers",
    ],
    "all": [
        "Ship in a storm",
        "Orientalism",
        "Hindu deity",
        "Ancient Rome",
        "Birds",
        "War",
        "Music",
        "Moonlight by the sea",
        "Calligraphy",
        "Martin Luther",
        "Fauvism",
        "Cubism",
        "Reading child",
        "Impressionism",
        "Blue dress",
        "Death",
        "Nature morte",
        "Woman by a window",
        "Painter",
        "Inside cathedral",
        "Elephant",
        "Crucifixion",
    ],
}

# Add work types not in English or with non-standard pluralization
WORK_TYPES_DICT = {
    "ornamenttekening": {
        "eng_sing": "ornamental drawing",
        "eng_plural": "ornamental drawings",
    },
    "albumblad": {"eng_sing": "album leaf", "eng_plural": "album leaves"},
    "reverse painting on glass": {
        "eng_sing": "reverse painting on glass",
        "eng_plural": "reverse paintings on glass",
    },
    "zijpaneel": {"eng_sing": "side panel", "eng_plural": "side panels"},
    "aquarel": {"eng_sing": "watercolor", "eng_plural": "watercolors"},
    "ceiling painting": {
        "eng_sing": "ceiling painting",
        "eng_plural": "ceiling paintings",
    },
    "penschildering": {"eng_sing": "pen painting", "eng_plural": "pen paintings"},
    "decoratiestuk": {
        "eng_sing": "decorative piece",
        "eng_plural": "decorative pieces",
    },
    "preparatory study": {
        "eng_sing": "preparatory study",
        "eng_plural": "preparatory studies",
    },
    "historieplaat": {"eng_sing": "history panel", "eng_plural": "history panels"},
    "interieuronderdeel": {
        "eng_sing": "interior element",
        "eng_plural": "interior elements",
    },
    "overmantel": {"eng_sing": "overmantel", "eng_plural": "overmantels"},
    "tondi": {"eng_sing": "tondo", "eng_plural": "tondi"},
    "sketch": {"eng_sing": "sketch", "eng_plural": "sketches"},
    "betimmering": {"eng_sing": "paneling", "eng_plural": "panelings"},
    "box": {"eng_sing": "box", "eng_plural": "boxes"},
    "heraldisch object": {
        "eng_sing": "heraldic object",
        "eng_plural": "heraldic objects",
    },
    "family arms": {"eng_sing": "family arms", "eng_plural": "family arms"},
    "plate (dishes)": {"eng_sing": "plate (dishes)", "eng_plural": "plates (dishes)"},
    "silhouette": {"eng_sing": "silhouette", "eng_plural": "silhouettes"},
    "memoriestuk": {"eng_sing": "memorial piece", "eng_plural": "memorial pieces"},
    "historieprent": {
        "eng_sing": "historical print",
        "eng_plural": "historical prints",
    },
    "schroefdaalder": {
        "eng_sing": "screw daalder (coin type)",
        "eng_plural": "screw daalders",
    },
    "reproductie": {"eng_sing": "reproduction", "eng_plural": "reproductions"},
    "schoorsteen": {"eng_sing": "chimney", "eng_plural": "chimneys"},
    "pier glass": {"eng_sing": "pier glass", "eng_plural": "pier glasses"},
    "perspectiefkast": {
        "eng_sing": "perspective box",
        "eng_plural": "perspective boxes",
    },
    "cassone": {"eng_sing": "cassone", "eng_plural": "cassoni"},
    "wrijfprent": {"eng_sing": "rubbing print", "eng_plural": "rubbing prints"},
    "Xiwangmu": {"eng_sing": "Xiwangmu", "eng_plural": "Xiwangmu figures"},
    "book of hours": {"eng_sing": "book of hours", "eng_plural": "books of hours"},
    "beschilderde katoen": {
        "eng_sing": "painted cotton",
        "eng_plural": "painted cottons",
    },
    "kakemono": {"eng_sing": "kakemono", "eng_plural": "kakemonos"},
    "locket": {"eng_sing": "locket", "eng_plural": "lockets"},
    "uithangbord": {"eng_sing": "signboard", "eng_plural": "signboards"},
    "study": {"eng_sing": "study", "eng_plural": "studies"},
    "kopie naar fresco": {
        "eng_sing": "copy after fresco",
        "eng_plural": "copies after frescoes",
    },
    "kopie naar tekening": {
        "eng_sing": "copy after drawing",
        "eng_plural": "copies after drawings",
    },
    "kopie naar prent": {
        "eng_sing": "copy after print",
        "eng_plural": "copies after prints",
    },
    "schetsboekblad": {"eng_sing": "sketchbook page", "eng_plural": "sketchbook pages"},
    "copy": {"eng_sing": "copy", "eng_plural": "copies"},
    "predella": {"eng_sing": "predella", "eng_plural": "predellas"},
    "brooch": {"eng_sing": "brooch", "eng_plural": "brooches"},
    "Boeddha-beeld": {"eng_sing": "Buddha statue", "eng_plural": "Buddha statues"},
    "theebus": {"eng_sing": "tea caddy", "eng_plural": "tea caddies"},
    "folder (container)": {
        "eng_sing": "folder (container)",
        "eng_plural": "folders (containers)",
    },
    "tegning": {"eng_sing": "drawing", "eng_plural": "drawings"},
    "maleri": {"eng_sing": "painting", "eng_plural": "paintings"},
    "akvarel": {"eng_sing": "watercolor", "eng_plural": "watercolors"},
    "buste": {"eng_sing": "bust", "eng_plural": "busts"},
    "akvatinte": {"eng_sing": "aquatint", "eng_plural": "aquatints"},
    "altertavle (maleri)": {
        "eng_sing": "altarpiece",
        "eng_plural": "altarpieces",
    },
    "pastel": {"eng_sing": "pastel", "eng_plural": "pastels"},
    "grafik": {"eng_sing": "print", "eng_plural": "prints"},
    "design": {"eng_sing": "design", "eng_plural": "designs"},
    "drawing": {"eng_sing": "drawing", "eng_plural": "drawings"},
    "painting": {"eng_sing": "painting", "eng_plural": "paintings"},
    "print": {"eng_sing": "print", "eng_plural": "prints"},
    "boekillustratie (ontwerp)": {
        "eng_sing": "book illustration (design)",
        "eng_plural": "book illustrations (designs)",
    },
    "design drawing": {
        "eng_sing": "design drawing",
        "eng_plural": "design drawings",
    },
    "cartoon": {"eng_sing": "cartoon", "eng_plural": "cartoons"},
    "finger painting": {
        "eng_sing": "finger painting",
        "eng_plural": "finger paintings",
    },
    "gouache": {"eng_sing": "gouache", "eng_plural": "gouaches"},
    "game": {"eng_sing": "game", "eng_plural": "games"},
    "grisaille": {"eng_sing": "grisaille", "eng_plural": "grisaille"},
    "calligraphy": {"eng_sing": "calligraphy", "eng_plural": "calligraphies"},
    "poem": {"eng_sing": "poem", "eng_plural": "poems"},
    "figuurstudie": {
        "eng_sing": "figure study",
        "eng_plural": "figure studies",
    },
    "miniature (painting)": {
        "eng_sing": "miniature (painting)",
        "eng_plural": "miniatures (paintings)",
    },
    "Indian miniature": {
        "eng_sing": "Indian miniature",
        "eng_plural": "Indian miniatures",
    },
    "Persian miniature": {
        "eng_sing": "Persian miniature",
        "eng_plural": "Persian miniatures",
    },
    "study for binding design": {
        "eng_sing": "study for binding design",
        "eng_plural": "studies for binding design",
    },
    "boekrug (ontwerp)": {
        "eng_sing": "book spine (design)",
        "eng_plural": "book spines (designs)",
    },
    "persian miniature": {
        "eng_sing": "Persian miniature",
        "eng_plural": "Persian miniatures",
    },
    "area plan": {"eng_sing": "area plan", "eng_plural": "area plans"},
    "letter": {"eng_sing": "letter", "eng_plural": "letters"},
    "cut-paper work": {
        "eng_sing": "cut-paper work",
        "eng_plural": "cut-paper works",
    },
    "map": {"eng_sing": "map", "eng_plural": "maps"},
    "nieuwjaarswens": {
        "eng_sing": "New Year's wish",
        "eng_plural": "New Year's wishes",
    },
    "postcard": {"eng_sing": "postcard", "eng_plural": "postcards"},
    "topographical view": {
        "eng_sing": "topographical view",
        "eng_plural": "topographical views",
    },
    "album": {"eng_sing": "album", "eng_plural": "albums"},
    "wall decoration": {
        "eng_sing": "wall decoration",
        "eng_plural": "wall decorations",
    },
    "menukaart": {"eng_sing": "menu card", "eng_plural": "menu cards"},
    "kostuumstudie": {
        "eng_sing": "costume study",
        "eng_plural": "costume studies",
    },
    "musical instrument": {
        "eng_sing": "musical instrument",
        "eng_plural": "musical instruments",
    },
    "stringed instrument": {
        "eng_sing": "stringed instrument",
        "eng_plural": "stringed instruments",
    },
    "keyboard instrument": {
        "eng_sing": "keyboard instrument",
        "eng_plural": "keyboard instruments",
    },
    "harpsichord": {"eng_sing": "harpsichord", "eng_plural": "harpsichords"},
    "harpsichord lid": {
        "eng_sing": "harpsichord lid",
        "eng_plural": "harpsichord lids",
    },
    "bookplate": {"eng_sing": "bookplate", "eng_plural": "bookplates"},
    "kostuumprent": {
        "eng_sing": "costume print",
        "eng_plural": "costume prints",
    },
    "titelpagina": {
        "eng_sing": "title page",
        "eng_plural": "title pages",
    },
    "photograph": {"eng_sing": "photograph", "eng_plural": "photographs"},
    "envelope": {"eng_sing": "envelope", "eng_plural": "envelopes"},
    "historisch objectvoorstelling": {
        "eng_sing": "historical object representation",
        "eng_plural": "historical object representations",
    },
    "ricordo": {"eng_sing": "ricordo", "eng_plural": "ricordi"},
    "illustratie (ontwerp)": {
        "eng_sing": "illustration (design)",
        "eng_plural": "illustrations (designs)",
    },
    "muziekblad": {"eng_sing": "music sheet", "eng_plural": "music sheets"},
    "frame": {"eng_sing": "frame", "eng_plural": "frames"},
    "overdoor": {"eng_sing": "overdoor", "eng_plural": "overdoors"},
    "dierstudie": {"eng_sing": "animal study", "eng_plural": "animal studies"},
    "vidimus": {"eng_sing": "vidimus", "eng_plural": "vidimus"},
    "clipping": {"eng_sing": "clipping", "eng_plural": "clippings"},
    "visiting card": {
        "eng_sing": "visiting card",
        "eng_plural": "visiting cards",
    },
    "photomechanical print": {
        "eng_sing": "photomechanical print",
        "eng_plural": "photomechanical prints",
    },
    "tracing": {"eng_sing": "tracing", "eng_plural": "tracings"},
    "triptych": {"eng_sing": "triptych", "eng_plural": "triptychs"},
    "centerpiece": {"eng_sing": "centerpiece", "eng_plural": "centerpieces"},
    "miniature": {"eng_sing": "miniature", "eng_plural": "miniatures"},
    "illuminated manuscript": {
        "eng_sing": "illuminated manuscript",
        "eng_plural": "illuminated manuscripts",
    },
    "sketchbook": {"eng_sing": "sketchbook", "eng_plural": "sketchbooks"},
    "schetsblad": {"eng_sing": "sketch sheet", "eng_plural": "sketch sheets"},
    "architectuurtekening": {
        "eng_sing": "architectural drawing",
        "eng_plural": "architectural drawings",
    },
    "manuscript": {"eng_sing": "manuscript", "eng_plural": "manuscripts"},
    "book": {"eng_sing": "book", "eng_plural": "books"},
    "photocollage": {
        "eng_sing": "photocollage",
        "eng_plural": "photocollages",
    },
    "page": {"eng_sing": "page", "eng_plural": "pages"},
    "invitation": {"eng_sing": "invitation", "eng_plural": "invitations"},
    "lunette": {"eng_sing": "lunette", "eng_plural": "lunettes"},
    "voorstudie (schilderij)": {
        "eng_sing": "preparatory study (painting)",
        "eng_plural": "preparatory studies (paintings)",
    },
    "illustration": {"eng_sing": "illustration", "eng_plural": "illustrations"},
    "prentbriefkaart": {
        "eng_sing": "illustrated postcard",
        "eng_plural": "illustrated postcards",
    },
    "text sheet": {"eng_sing": "text sheet", "eng_plural": "text sheets"},
    "fragment": {"eng_sing": "fragment", "eng_plural": "fragments"},
    "mural painting": {
        "eng_sing": "mural painting",
        "eng_plural": "mural paintings",
    },
    "account": {"eng_sing": "account", "eng_plural": "accounts"},
    "waaierblad": {"eng_sing": "fan leaf", "eng_plural": "fan leaves"},
    "poster": {"eng_sing": "poster", "eng_plural": "posters"},
    "document": {"eng_sing": "document", "eng_plural": "documents"},
    "tekst": {"eng_sing": "text", "eng_plural": "texts"},
    "hanging": {"eng_sing": "hanging", "eng_plural": "hangings"},
    "voorstudie (prent)": {
        "eng_sing": "preparatory study (print)",
        "eng_plural": "preparatory studies (prints)",
    },
    "ceiling": {"eng_sing": "ceiling", "eng_plural": "ceilings"},
    "architectural element": {
        "eng_sing": "architectural element",
        "eng_plural": "architectural elements",
    },
    "verzamelalbum": {
        "eng_sing": "collection album",
        "eng_plural": "collection albums",
    },
    "cartography": {"eng_sing": "cartography", "eng_plural": "cartographies"},
    "mirror": {"eng_sing": "mirror", "eng_plural": "mirrors"},
    "telegram": {"eng_sing": "telegram", "eng_plural": "telegrams"},
    "vignette": {"eng_sing": "vignette", "eng_plural": "vignettes"},
    "passe-partout": {"eng_sing": "passe-partout", "eng_plural": "passe-partouts"},
    "fashion plate": {"eng_sing": "fashion plate", "eng_plural": "fashion plates"},
    "kindertekening": {
        "eng_sing": "children's drawing",
        "eng_plural": "children's drawings",
    },
    "studbook": {"eng_sing": "studbook", "eng_plural": "studbooks"},
    "boekomslag (ontwerp)": {
        "eng_sing": "book cover (design)",
        "eng_plural": "book covers (designs)",
    },
    "metalpoint drawing": {
        "eng_sing": "metalpoint drawing",
        "eng_plural": "metalpoint drawings",
    },
    "door": {"eng_sing": "door", "eng_plural": "doors"},
    "mantel": {"eng_sing": "mantel", "eng_plural": "mantels"},
    "chimney wing": {"eng_sing": "chimney wing", "eng_plural": "chimney wings"},
    "window blind": {"eng_sing": "window blind", "eng_plural": "window blinds"},
    "pier table": {"eng_sing": "pier table", "eng_plural": "pier tables"},
    "overmantel mirror": {
        "eng_sing": "overmantel mirror",
        "eng_plural": "overmantel mirrors",
    },
    "light": {"eng_sing": "light", "eng_plural": "lights"},
    "working drawing": {
        "eng_sing": "working drawing",
        "eng_plural": "working drawings",
    },
    "lid": {"eng_sing": "lid", "eng_plural": "lids"},
    "virginal lid": {"eng_sing": "virginal lid", "eng_plural": "virginal lids"},
    "virginal": {"eng_sing": "virginal", "eng_plural": "virginals"},
    "caricature": {"eng_sing": "caricature", "eng_plural": "caricatures"},
    "greeting card": {"eng_sing": "greeting card", "eng_plural": "greeting cards"},
    "diptych": {"eng_sing": "diptych", "eng_plural": "diptychs"},
    "plaque": {"eng_sing": "plaque", "eng_plural": "plaques"},
    "wensbrief": {"eng_sing": "wish letter", "eng_plural": "wish letters"},
    "coin": {"eng_sing": "coin", "eng_plural": "coins"},
    "tangka": {"eng_sing": "tangka", "eng_plural": "tangkas"},
    "preliminary drawing": {
        "eng_sing": "preliminary drawing",
        "eng_plural": "preliminary drawings",
    },
    "trompe-l'oeil": {"eng_sing": "trompe-l'oeil", "eng_plural": "trompe-l'oeils"},
    "medal": {"eng_sing": "medal", "eng_plural": "medals"},
    "tableau": {"eng_sing": "tableau", "eng_plural": "tableaux"},
    "business card": {"eng_sing": "business card", "eng_plural": "business cards"},
    "rebus": {"eng_sing": "rebus", "eng_plural": "rebuses"},
    "correspondence": {"eng_sing": "correspondence", "eng_plural": "correspondences"},
    "kunsthistorische verhandeling": {
        "eng_sing": "art historical treatise",
        "eng_plural": "art historical treatises",
    },
    "boekillustratie": {
        "eng_sing": "book illustration",
        "eng_plural": "book illustrations",
    },
    "form": {"eng_sing": "form", "eng_plural": "forms"},
    "tools": {"eng_sing": "tool", "eng_plural": "tools"},
    "kopie naar schilderij": {
        "eng_sing": "copy after painting",
        "eng_plural": "copies after paintings",
    },
    "playing card": {"eng_sing": "playing card", "eng_plural": "playing cards"},
    "oil painting": {"eng_sing": "oil painting", "eng_plural": "oil paintings"},
    "diary": {"eng_sing": "diary", "eng_plural": "diaries"},
    "stamp": {"eng_sing": "stamp", "eng_plural": "stamps"},
    "binding": {"eng_sing": "binding", "eng_plural": "bindings"},
    "Christmas card": {"eng_sing": "Christmas card", "eng_plural": "Christmas cards"},
    "construction drawing": {
        "eng_sing": "construction drawing",
        "eng_plural": "construction drawings",
    },
    "tanka": {"eng_sing": "tanka", "eng_plural": "tankas"},
    "wrapper": {"eng_sing": "wrapper", "eng_plural": "wrappers"},
    "kwitantie": {"eng_sing": "receipt", "eng_plural": "receipts"},
    "hanging scroll": {"eng_sing": "hanging scroll", "eng_plural": "hanging scrolls"},
    "fan": {"eng_sing": "fan", "eng_plural": "fans"},
    "decoratief object": {
        "eng_sing": "decorative object",
        "eng_plural": "decorative objects",
    },
    "panorama": {"eng_sing": "panorama", "eng_plural": "panoramas"},
    "brunaille": {"eng_sing": "brunaille", "eng_plural": "brunailles"},
    "aantekening": {"eng_sing": "note", "eng_plural": "notes"},
    "collage (visual work)": {
        "eng_sing": "collage (visual work)",
        "eng_plural": "collages (visual works)",
    },
    "kunstenaarskarikatuur": {
        "eng_sing": "artist's caricature",
        "eng_plural": "artists' caricatures",
    },
    "admission ticket": {
        "eng_sing": "admission ticket",
        "eng_plural": "admission tickets",
    },
    "pyx": {"eng_sing": "pyx", "eng_plural": "pyxes"},
    "communion card": {"eng_sing": "communion card", "eng_plural": "communion cards"},
    "replica": {"eng_sing": "replica", "eng_plural": "replicas"},
    "charter": {"eng_sing": "charter", "eng_plural": "charters"},
}
